import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("cleaned_orders.xlsx")
print(df.head())
print(df.info())
print(df.describe())
plt.figure(figsize=(8,5))
sns.countplot(x="OrderStatus", data=df)
plt.title("Order Status Distribution")
plt.show()
plt.figure(figsize=(8,5))
sns.histplot(df["TotalPrice"], bins=20)
plt.title("Distribution of Total Price")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x="Product", data=df)
plt.title("Products Ordered")
plt.xticks(rotation=45)
plt.show()
plt.figure(figsize=(8,5))
sns.scatterplot(x="Quantity", y="TotalPrice", data=df)
plt.title("Quantity vs Total Price")
plt.show()
plt.figure(figsize=(8,5))
sns.countplot(x="PaymentMethod", data=df)
plt.title("Payment Method Distribution")
plt.xticks(rotation=45)
plt.show()
sales = df.groupby("Product")["TotalPrice"].sum()

plt.figure(figsize=(10,5))
sales.plot(kind="bar")
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.show()
plt.figure(figsize=(10,5))
sns.countplot(x="ReferralSource", data=df)
plt.title("Referral Source Distribution")
plt.xticks(rotation=45)
plt.show()
correlation = df[["Quantity", "UnitPrice", "ItemsInCart", "TotalPrice"]].corr()

plt.figure(figsize=(8,6))
sns.heatmap(correlation, annot=True, cmap="Blues")
plt.title("Correlation Heatmap")
plt.show()
df["Date"] = pd.to_datetime(df["Date"])

df["Month"] = df["Date"].dt.to_period("M")

monthly_sales = df.groupby("Month")["TotalPrice"].sum()

plt.figure(figsize=(10,5))
monthly_sales.plot(kind="line", marker="o")
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.show()
plt.figure(figsize=(8,5))
sns.boxplot(y=df["TotalPrice"])
plt.title("Outliers in Total Price")
plt.show()